{
  parserClass="com.aopphp.go.parser.PointcutParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="GoAop"
  psiImplClassSuffix="Impl"
  psiPackage="com.aopphp.go.psi"
  psiImplPackage="com.aopphp.go.psi.impl"

  elementTypeHolderClass="com.aopphp.go.psi.GoAopTypes"
  elementTypeClass="com.aopphp.go.psi.GoAopElementType"
  tokenTypeClass="com.aopphp.go.psi.GoAopTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY