[versions]
# libraries
annotations = "26.1.0"
junit5 = "6.1.0"
mockitoKotlin = "6.3.0"

# plugins
kotlin = "2.4.0"
changelog = "2.5.0"
intellijPlatformGradle = "2.17.0"
qodana = "2026.1.3"
kover = "0.9.8"
grammarkit = "2023.3.0.3"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
junit5-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit5" }
junit5-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "6.1.0" }
junit4 = { group = "junit", name = "junit", version = "4.13.2" }
junitVintageEngine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit5" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatformGradle = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatformGradle" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
