[versions]
# libraries
annotations = "24.1.0"

# plugins
kotlin = "2.2.0"
changelog = "2.2.0"
intellijPlatformGradle = "2.13.1"
qodana = "2023.3.1"
kover = "0.7.6"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatformGradle = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatformGradle" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
