/* The following code was generated by JFlex 1.4.3 on 14.05.15 12:47 */

package com.aopphp.go.parser;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.aopphp.go.psi.PointcutTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 14.05.15 12:47 from the specification file
 * <tt>H:/Work/idea-go-aop-plugin/src/com/aopphp/go/parser/PointcutLexer.flex</tt>
 */
public class PointcutLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\1\0\1\1\1\1\22\0\1\1\1\16\4\0"+
    "\1\17\1\0\1\10\1\11\1\15\1\21\1\0\1\12\1\0\1\3"+
    "\12\5\1\14\3\0\1\13\1\0\1\7\32\4\1\0\1\6\2\0"+
    "\1\4\1\0\1\22\1\41\1\23\1\42\1\24\1\40\1\4\1\35"+
    "\1\31\2\4\1\36\1\44\1\33\1\32\1\45\1\4\1\46\1\25"+
    "\1\30\1\27\1\47\1\34\1\26\1\43\1\37\1\0\1\20\2\0"+
    "\201\4\uff00\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\2\1\1\10\1\11\2\1\1\12\11\3\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\46\3\1\21\4\3"+
    "\1\22\4\3\1\23\1\3\1\24\6\3\1\25\1\26"+
    "\7\3\1\27\2\3\1\30\1\31\11\3\1\32\5\3"+
    "\1\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\50\0\50\0\50"+
    "\0\50\0\310\0\360\0\u0118\0\50\0\u0140\0\u0168\0\50"+
    "\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8"+
    "\0\u02d0\0\u02f8\0\50\0\50\0\50\0\50\0\50\0\u0320"+
    "\0\u0348\0\u0370\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460"+
    "\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0"+
    "\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0"+
    "\0\u0708\0\u0730\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820"+
    "\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8\0\240\0\u0910\0\u0938"+
    "\0\u0960\0\u0988\0\240\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\240"+
    "\0\u0a50\0\240\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18\0\u0b40"+
    "\0\240\0\240\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08\0\u0c30"+
    "\0\u0c58\0\240\0\u0c80\0\u0ca8\0\240\0\240\0\u0cd0\0\u0cf8"+
    "\0\u0d20\0\u0d48\0\u0d70\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\240"+
    "\0\u0e38\0\u0e60\0\u0e88\0\u0eb0\0\u0ed8\0\240";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\1\2\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\3\5\1\25\2\5"+
    "\1\26\3\5\1\27\1\5\1\30\2\5\1\31\2\5"+
    "\51\0\2\3\50\0\1\32\50\0\2\5\14\0\26\5"+
    "\13\0\1\33\50\0\1\34\50\0\1\35\51\0\1\36"+
    "\50\0\1\37\33\0\2\5\14\0\1\5\1\40\24\5"+
    "\4\0\2\5\14\0\16\5\1\41\7\5\4\0\2\5"+
    "\14\0\4\5\1\42\21\5\4\0\2\5\14\0\6\5"+
    "\1\43\17\5\4\0\2\5\14\0\11\5\1\44\14\5"+
    "\4\0\2\5\14\0\7\5\1\45\16\5\4\0\2\5"+
    "\14\0\7\5\1\46\16\5\4\0\2\5\14\0\21\5"+
    "\1\47\4\5\4\0\2\5\14\0\5\5\1\50\16\5"+
    "\1\51\1\5\2\32\1\0\45\32\4\0\2\5\14\0"+
    "\1\5\1\52\24\5\4\0\2\5\14\0\14\5\1\53"+
    "\11\5\4\0\2\5\14\0\2\5\1\54\23\5\4\0"+
    "\2\5\14\0\1\55\25\5\4\0\2\5\14\0\7\5"+
    "\1\56\16\5\4\0\2\5\14\0\6\5\1\57\17\5"+
    "\4\0\2\5\14\0\11\5\1\60\14\5\4\0\2\5"+
    "\14\0\11\5\1\61\14\5\4\0\2\5\14\0\17\5"+
    "\1\62\6\5\4\0\2\5\14\0\7\5\1\63\1\64"+
    "\15\5\4\0\2\5\14\0\2\5\1\65\23\5\4\0"+
    "\2\5\14\0\10\5\1\66\15\5\4\0\2\5\14\0"+
    "\1\5\1\67\24\5\4\0\2\5\14\0\6\5\1\70"+
    "\17\5\4\0\2\5\14\0\6\5\1\71\17\5\4\0"+
    "\2\5\14\0\13\5\1\72\12\5\4\0\2\5\14\0"+
    "\1\73\25\5\4\0\2\5\14\0\1\74\25\5\4\0"+
    "\2\5\14\0\14\5\1\75\11\5\4\0\2\5\14\0"+
    "\25\5\1\76\4\0\2\5\14\0\6\5\1\77\17\5"+
    "\4\0\2\5\14\0\3\5\1\100\22\5\4\0\2\5"+
    "\14\0\12\5\1\101\13\5\4\0\2\5\14\0\5\5"+
    "\1\102\20\5\4\0\2\5\14\0\7\5\1\103\16\5"+
    "\4\0\2\5\14\0\7\5\1\104\16\5\4\0\2\5"+
    "\14\0\7\5\1\105\16\5\4\0\2\5\14\0\14\5"+
    "\1\106\11\5\4\0\2\5\14\0\22\5\1\107\3\5"+
    "\4\0\2\5\14\0\7\5\1\110\16\5\4\0\2\5"+
    "\14\0\1\111\25\5\4\0\2\5\14\0\2\5\1\112"+
    "\23\5\4\0\2\5\14\0\3\5\1\113\22\5\4\0"+
    "\2\5\14\0\17\5\1\114\6\5\4\0\2\5\14\0"+
    "\6\5\1\115\17\5\4\0\2\5\14\0\1\5\1\116"+
    "\24\5\4\0\2\5\14\0\1\117\25\5\4\0\2\5"+
    "\14\0\11\5\1\120\14\5\4\0\2\5\14\0\7\5"+
    "\1\121\16\5\4\0\2\5\14\0\1\5\1\122\24\5"+
    "\4\0\2\5\14\0\6\5\1\123\17\5\4\0\2\5"+
    "\14\0\1\5\1\124\24\5\4\0\2\5\14\0\2\5"+
    "\1\125\23\5\4\0\2\5\14\0\7\5\1\126\16\5"+
    "\4\0\2\5\14\0\7\5\1\127\16\5\4\0\2\5"+
    "\14\0\14\5\1\130\11\5\4\0\2\5\14\0\1\5"+
    "\1\131\24\5\4\0\2\5\14\0\2\5\1\132\23\5"+
    "\4\0\2\5\14\0\6\5\1\133\17\5\4\0\2\5"+
    "\14\0\14\5\1\134\11\5\4\0\2\5\14\0\10\5"+
    "\1\135\15\5\4\0\2\5\14\0\11\5\1\136\14\5"+
    "\4\0\2\5\14\0\7\5\1\137\16\5\4\0\2\5"+
    "\14\0\2\5\1\140\23\5\4\0\2\5\14\0\10\5"+
    "\1\141\15\5\4\0\2\5\14\0\11\5\1\142\14\5"+
    "\4\0\2\5\14\0\7\5\1\143\16\5\4\0\2\5"+
    "\14\0\15\5\1\144\10\5\4\0\2\5\14\0\20\5"+
    "\1\145\5\5\4\0\2\5\14\0\12\5\1\146\13\5"+
    "\4\0\2\5\14\0\6\5\1\147\17\5\4\0\2\5"+
    "\14\0\1\150\25\5\4\0\2\5\14\0\7\5\1\151"+
    "\16\5\4\0\2\5\14\0\6\5\1\152\17\5\4\0"+
    "\2\5\14\0\1\153\25\5\4\0\2\5\14\0\7\5"+
    "\1\154\16\5\4\0\2\5\14\0\14\5\1\155\11\5"+
    "\4\0\2\5\14\0\10\5\1\156\15\5\4\0\2\5"+
    "\14\0\7\5\1\157\16\5\4\0\2\5\14\0\11\5"+
    "\1\160\14\5\4\0\2\5\14\0\15\5\1\161\10\5"+
    "\4\0\2\5\14\0\1\162\25\5\4\0\2\5\14\0"+
    "\6\5\1\163\17\5\4\0\2\5\14\0\7\5\1\164"+
    "\16\5\4\0\2\5\14\0\10\5\1\165\15\5\4\0"+
    "\2\5\14\0\11\5\1\166\14\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3840];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\4\11\3\1\1\11\2\1\1\11"+
    "\12\1\5\11\127\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public PointcutLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PointcutLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { return com.aopphp.go.psi.PointcutTypes.WITHIN;
          }
        case 28: break;
        case 27: 
          { return com.aopphp.go.psi.PointcutTypes.STATICINITIALIZATION;
          }
        case 29: break;
        case 5: 
          { return com.aopphp.go.psi.PointcutTypes.ANNOTATION;
          }
        case 30: break;
        case 16: 
          { return com.aopphp.go.psi.PointcutTypes.DISJUNCTION;
          }
        case 31: break;
        case 20: 
          { return com.aopphp.go.psi.PointcutTypes.PUBLIC;
          }
        case 32: break;
        case 7: 
          { return com.aopphp.go.psi.PointcutTypes.RP;
          }
        case 33: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 34: break;
        case 10: 
          { return com.aopphp.go.psi.PointcutTypes.SUBCLASSFILTER;
          }
        case 35: break;
        case 4: 
          { return com.aopphp.go.psi.PointcutTypes.NSSEPARATOR;
          }
        case 36: break;
        case 24: 
          { return com.aopphp.go.psi.PointcutTypes.PROTECTED;
          }
        case 37: break;
        case 11: 
          { return com.aopphp.go.psi.PointcutTypes.COMMENT;
          }
        case 38: break;
        case 25: 
          { return com.aopphp.go.psi.PointcutTypes.CFLOWBELOW;
          }
        case 39: break;
        case 18: 
          { return com.aopphp.go.psi.PointcutTypes.ACCESS;
          }
        case 40: break;
        case 26: 
          { return com.aopphp.go.psi.PointcutTypes.INITIALIZATION;
          }
        case 41: break;
        case 13: 
          { return com.aopphp.go.psi.PointcutTypes.STATICACCESS;
          }
        case 42: break;
        case 21: 
          { return com.aopphp.go.psi.PointcutTypes.DYNAMIC;
          }
        case 43: break;
        case 15: 
          { return com.aopphp.go.psi.PointcutTypes.CONJUNCTION;
          }
        case 44: break;
        case 8: 
          { return com.aopphp.go.psi.PointcutTypes.ASTERISK;
          }
        case 45: break;
        case 23: 
          { return com.aopphp.go.psi.PointcutTypes.EXECUTION;
          }
        case 46: break;
        case 14: 
          { return com.aopphp.go.psi.PointcutTypes.DOUBLEASTERISK;
          }
        case 47: break;
        case 17: 
          { return com.aopphp.go.psi.PointcutTypes.FINAL;
          }
        case 48: break;
        case 9: 
          { return com.aopphp.go.psi.PointcutTypes.NEGATION;
          }
        case 49: break;
        case 22: 
          { return com.aopphp.go.psi.PointcutTypes.PRIVATE;
          }
        case 50: break;
        case 3: 
          { return com.aopphp.go.psi.PointcutTypes.NAMEPART;
          }
        case 51: break;
        case 6: 
          { return com.aopphp.go.psi.PointcutTypes.LP;
          }
        case 52: break;
        case 12: 
          { return com.aopphp.go.psi.PointcutTypes.OBJECTACCESS;
          }
        case 53: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 54: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
