// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: src/main/java/com/aopphp/go/parser/PointcutLexer.flex

package com.aopphp.go.parser;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.aopphp.go.psi.PointcutTypes.*;


public class PointcutLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\2\0\1\5\1\0\1\6\1\0\1\7\1\10\1\11"+
    "\1\12\1\0\1\13\1\0\1\14\12\15\1\16\3\0"+
    "\1\17\1\20\1\21\10\22\1\23\21\22\1\0\1\24"+
    "\2\0\1\22\1\0\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\22\1\33\1\34\2\22\1\35\1\36\1\37"+
    "\1\40\1\41\1\22\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\0\1\53\2\0\6\22"+
    "\1\54\172\22\u0128\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\5\1\6"+
    "\1\7\2\1\1\10\1\11\1\12\1\13\1\14\12\13"+
    "\1\15\1\0\1\16\1\17\1\20\1\21\1\22\13\13"+
    "\1\23\1\0\14\13\1\0\14\13\1\24\4\13\1\25"+
    "\7\13\1\26\7\13\1\27\1\13\1\30\1\13\1\31"+
    "\3\13\1\32\11\13\1\33\2\13\1\34\1\13\1\35"+
    "\14\13\1\36\1\37\6\13\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[138];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\55\0\207\0\264\0\55\0\55"+
    "\0\341\0\55\0\u010e\0\u013b\0\u0168\0\55\0\55\0\u0195"+
    "\0\55\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276\0\u02a3\0\u02d0"+
    "\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1\0\55\0\55\0\55"+
    "\0\u03de\0\55\0\u040b\0\u0438\0\u0465\0\u0492\0\u04bf\0\u04ec"+
    "\0\u0519\0\u0546\0\u0573\0\u05a0\0\u05cd\0\55\0\u05fa\0\u0627"+
    "\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762\0\u078f"+
    "\0\u07bc\0\u07e9\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7"+
    "\0\u0924\0\u0951\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32\0\u0a5f"+
    "\0\55\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13\0\u0195\0\u0b40\0\u0b6d"+
    "\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21\0\u0c4e\0\u0195\0\u0c7b\0\u0ca8"+
    "\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89\0\u0195\0\u0db6\0\u0195"+
    "\0\u0de3\0\u0195\0\u0e10\0\u0e3d\0\u0e6a\0\u0195\0\u0e97\0\u0ec4"+
    "\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff\0\u0195"+
    "\0\u102c\0\u1059\0\u0195\0\u1086\0\u0195\0\u10b3\0\u10e0\0\u110d"+
    "\0\u113a\0\u1167\0\u1194\0\u11c1\0\u11ee\0\u121b\0\u1248\0\u1275"+
    "\0\u12a2\0\u0195\0\u0195\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u1383"+
    "\0\u13b0\0\u0195";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[138];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\2\1\15\1\2\1\16"+
    "\1\17\2\20\1\21\1\22\1\20\1\23\1\24\1\25"+
    "\1\26\1\20\1\27\1\20\1\30\2\20\1\31\1\20"+
    "\1\32\3\20\1\33\3\20\1\34\1\20\56\0\2\3"+
    "\116\0\1\35\16\0\1\36\57\0\1\37\62\0\1\40"+
    "\51\0\1\41\56\0\1\42\53\0\1\20\4\0\2\20"+
    "\1\0\26\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\2\20\1\43\23\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\5\20\1\44\20\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\24\20\1\45\1\20"+
    "\1\0\1\20\15\0\1\20\4\0\2\20\1\0\23\20"+
    "\1\46\2\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\7\20\1\47\16\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\12\20\1\50\13\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\1\51\25\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\15\20\1\52"+
    "\2\20\1\53\5\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\17\20\1\54\6\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\7\20\1\55\16\20\1\0"+
    "\1\20\53\0\1\56\34\0\1\57\21\0\2\41\2\0"+
    "\50\41\16\0\1\20\4\0\2\20\1\0\2\20\1\60"+
    "\23\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\10\20\1\61\15\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\12\20\1\62\13\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\4\20\1\63\21\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\12\20\1\64"+
    "\13\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\7\20\1\65\16\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\17\20\1\66\6\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\7\20\1\67\3\20\1\70"+
    "\12\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\1\20\1\71\24\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\1\72\25\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\17\20\1\73\6\20\1\0\1\20"+
    "\34\0\1\74\35\0\1\20\4\0\2\20\1\0\4\20"+
    "\1\75\21\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\13\20\1\76\12\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\1\77\25\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\2\20\1\100\23\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\1\101\25\20"+
    "\1\0\1\20\15\0\1\20\4\0\2\20\1\0\17\20"+
    "\1\102\6\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\2\20\1\103\23\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\21\20\1\104\4\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\17\20\1\105\6\20"+
    "\1\0\1\20\15\0\1\20\4\0\2\20\1\0\10\20"+
    "\1\106\15\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\17\20\1\107\6\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\6\20\1\110\17\20\1\0\1\20"+
    "\43\0\1\111\26\0\1\20\4\0\2\20\1\0\16\20"+
    "\1\112\7\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\22\20\1\113\3\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\11\20\1\114\14\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\20\20\1\115\5\20"+
    "\1\0\1\20\15\0\1\20\4\0\2\20\1\0\10\20"+
    "\1\116\15\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\7\20\1\117\16\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\6\20\1\120\17\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\1\121\25\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\4\20\1\122"+
    "\21\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\7\20\1\123\16\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\7\20\1\124\16\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\7\20\1\125\16\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\16\20\1\126"+
    "\7\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\1\20\1\127\24\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\7\20\1\130\16\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\17\20\1\131\6\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\1\132\25\20"+
    "\1\0\1\20\15\0\1\20\4\0\1\20\1\133\1\0"+
    "\26\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\17\20\1\134\6\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\2\20\1\135\23\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\2\20\1\136\23\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\2\20\1\137"+
    "\23\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\12\20\1\140\13\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\4\20\1\141\21\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\2\20\1\142\23\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\7\20\1\143"+
    "\16\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\10\20\1\144\15\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\12\20\1\145\13\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\4\20\1\146\21\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\17\20\1\147"+
    "\6\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\7\20\1\150\16\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\10\20\1\151\15\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\13\20\1\152\12\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\7\20\1\153"+
    "\16\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\6\20\1\154\17\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\4\20\1\155\21\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\12\20\1\156\13\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\13\20\1\157"+
    "\12\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\12\20\1\160\13\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\25\20\1\161\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\4\20\1\162\21\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\3\20\1\163\22\20"+
    "\1\0\1\20\15\0\1\20\4\0\2\20\1\0\7\20"+
    "\1\164\16\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\22\20\1\165\3\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\1\166\25\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\15\20\1\167\10\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\17\20\1\170"+
    "\6\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\17\20\1\171\6\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\7\20\1\172\16\20\1\0\1\20\15\0"+
    "\1\20\4\0\2\20\1\0\7\20\1\173\16\20\1\0"+
    "\1\20\15\0\1\20\4\0\2\20\1\0\7\20\1\174"+
    "\16\20\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\17\20\1\175\6\20\1\0\1\20\15\0\1\20\4\0"+
    "\2\20\1\0\1\176\25\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\13\20\1\177\12\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\4\20\1\200\21\20"+
    "\1\0\1\20\15\0\1\20\4\0\2\20\1\0\10\20"+
    "\1\201\15\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\12\20\1\202\13\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\3\20\1\203\22\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\7\20\1\204\16\20"+
    "\1\0\1\20\15\0\1\20\4\0\2\20\1\0\25\20"+
    "\1\205\1\0\1\20\15\0\1\20\4\0\2\20\1\0"+
    "\1\206\25\20\1\0\1\20\15\0\1\20\4\0\2\20"+
    "\1\0\17\20\1\207\6\20\1\0\1\20\15\0\1\20"+
    "\4\0\2\20\1\0\7\20\1\210\16\20\1\0\1\20"+
    "\15\0\1\20\4\0\2\20\1\0\13\20\1\211\12\20"+
    "\1\0\1\20\15\0\1\20\4\0\2\20\1\0\12\20"+
    "\1\212\13\20\1\0\1\20";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5085];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\2\11\1\1\1\11"+
    "\3\1\2\11\1\1\1\11\13\1\1\0\3\11\1\1"+
    "\1\11\13\1\1\11\1\0\14\1\1\0\14\1\1\11"+
    "\101\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[138];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  public PointcutLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PointcutLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return com.intellij.psi.TokenType.BAD_CHARACTER;
            }
          // fall through
          case 33: break;
          case 2:
            { return com.intellij.psi.TokenType.WHITE_SPACE;
            }
          // fall through
          case 34: break;
          case 3:
            { return com.aopphp.go.psi.PointcutTypes.T_NEGATION;
            }
          // fall through
          case 35: break;
          case 4:
            { return com.aopphp.go.psi.PointcutTypes.T_LEFT_PAREN;
            }
          // fall through
          case 36: break;
          case 5:
            { return com.aopphp.go.psi.PointcutTypes.T_RIGHT_PAREN;
            }
          // fall through
          case 37: break;
          case 6:
            { return com.aopphp.go.psi.PointcutTypes.T_ASTERISK;
            }
          // fall through
          case 38: break;
          case 7:
            { return com.aopphp.go.psi.PointcutTypes.T_SUBNAMESPACE_SIGN;
            }
          // fall through
          case 39: break;
          case 8:
            { return com.aopphp.go.psi.PointcutTypes.T_COLON;
            }
          // fall through
          case 40: break;
          case 9:
            { return com.aopphp.go.psi.PointcutTypes.T_QUESTION_MARK;
            }
          // fall through
          case 41: break;
          case 10:
            { return com.aopphp.go.psi.PointcutTypes.T_ANNOTATION;
            }
          // fall through
          case 42: break;
          case 11:
            { return com.aopphp.go.psi.PointcutTypes.T_NAME_PART;
            }
          // fall through
          case 43: break;
          case 12:
            { return com.aopphp.go.psi.PointcutTypes.T_NS_SEPARATOR;
            }
          // fall through
          case 44: break;
          case 13:
            { return com.aopphp.go.psi.PointcutTypes.T_ALTERNATION;
            }
          // fall through
          case 45: break;
          case 14:
            { return com.aopphp.go.psi.PointcutTypes.T_LOGICAL_AND;
            }
          // fall through
          case 46: break;
          case 15:
            { return com.aopphp.go.psi.PointcutTypes.T_DOUBLE_ASTERISK;
            }
          // fall through
          case 47: break;
          case 16:
            { return com.aopphp.go.psi.PointcutTypes.T_OBJECT_ACCESS;
            }
          // fall through
          case 48: break;
          case 17:
            { return com.aopphp.go.psi.PointcutTypes.T_COMMENT;
            }
          // fall through
          case 49: break;
          case 18:
            { return com.aopphp.go.psi.PointcutTypes.T_STATIC_ACCESS;
            }
          // fall through
          case 50: break;
          case 19:
            { return com.aopphp.go.psi.PointcutTypes.T_LOGICAL_OR;
            }
          // fall through
          case 51: break;
          case 20:
            { return com.aopphp.go.psi.PointcutTypes.T_THIS;
            }
          // fall through
          case 52: break;
          case 21:
            { return com.aopphp.go.psi.PointcutTypes.FINAL;
            }
          // fall through
          case 53: break;
          case 22:
            { return com.aopphp.go.psi.PointcutTypes.ACCESS;
            }
          // fall through
          case 54: break;
          case 23:
            { return com.aopphp.go.psi.PointcutTypes.PUBLIC;
            }
          // fall through
          case 55: break;
          case 24:
            { return com.aopphp.go.psi.PointcutTypes.WITHIN;
            }
          // fall through
          case 56: break;
          case 25:
            { return com.aopphp.go.psi.PointcutTypes.DYNAMIC;
            }
          // fall through
          case 57: break;
          case 26:
            { return com.aopphp.go.psi.PointcutTypes.PRIVATE;
            }
          // fall through
          case 58: break;
          case 27:
            { return com.aopphp.go.psi.PointcutTypes.EXECUTION;
            }
          // fall through
          case 59: break;
          case 28:
            { return com.aopphp.go.psi.PointcutTypes.PROTECTED;
            }
          // fall through
          case 60: break;
          case 29:
            { return com.aopphp.go.psi.PointcutTypes.CFLOWBELOW;
            }
          // fall through
          case 61: break;
          case 30:
            { return com.aopphp.go.psi.PointcutTypes.INITIALIZATION;
            }
          // fall through
          case 62: break;
          case 31:
            { return com.aopphp.go.psi.PointcutTypes.MATCHINHERITED;
            }
          // fall through
          case 63: break;
          case 32:
            { return com.aopphp.go.psi.PointcutTypes.STATICINITIALIZATION;
            }
          // fall through
          case 64: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
